# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title GA (Eigen)
#' 
#' @description Simple genetic algorithm for maximising function. Implemented using the boost and Eigen libraries.
#' 
#' @param population_size The size of the population.
#' @param bitstring_size The size of the individual.
#' @param lower The lower bound of the interval.
#' @param upper The upper bound of the interval.
#' @param maximum_number_of_iterations The maximum allowed number of interations.
#' @param tolerance The convergence tolerance.
#' @param maximum_number_of_iterations_equal The number of iterations without changing the fittest individual before forced convergence.
#' 
#' @return A list with two elements: the fittest decoded individual found in the entire run and its fitness.
#' @export
GACppEigen <- function(population_size, bitstring_size, lower, upper, maximum_number_of_iterations, tolerance, maximum_number_of_iterations_equal) {
    .Call('_simpleGA_GACppEigen', PACKAGE = 'simpleGA', population_size, bitstring_size, lower, upper, maximum_number_of_iterations, tolerance, maximum_number_of_iterations_equal)
}

