# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title GA (Cpp)
#' 
#' @description Simple genetic algorithm for maximising function. Implemented using the boost and Eigen libraries.
#' 
#' @param population_size The size of the population.
#' @param bitstring_size The size of the individual.
#' @param lower The lower bound of the interval.
#' @param upper The upper bound of the interval.
#' @param maximum_number_of_iterations The maximum allowed number of interations.
#' @param tolerance The convergence tolerance.
#' @param maximum_number_of_iterations_equal The number of iterations without changing the fittest individual before forced convergence.
#' @param trace TRUE/FALSE: Show trace?
#' 
#' @return A vector with two elements: the fittest decoded individual found in the entire run and its fitness.
#' @export
#' @example inst/examples/GACpp.R
GA_Cpp <- function(population_size, bitstring_size, lower, upper, maximum_number_of_iterations, tolerance, maximum_number_of_iterations_equal, trace = FALSE) {
    .Call('_simpleGA_GA_Cpp', PACKAGE = 'simpleGA', population_size, bitstring_size, lower, upper, maximum_number_of_iterations, tolerance, maximum_number_of_iterations_equal, trace)
}

#' @title GA (Cpp -- extended)
#' 
#' @description Simple genetic algorithm for maximising function. Implemented using the boost and Eigen libraries.
#' 
#' @param population_size The size of the population.
#' @param bitstring_size The size of the individual.
#' @param fitness A univariate function to be maximised.
#' @param lower The lower bound of the interval.
#' @param upper The upper bound of the interval.
#' @param maximum_number_of_iterations The maximum allowed number of interations.
#' @param tolerance The convergence tolerance.
#' @param maximum_number_of_iterations_equal The number of iterations without changing the fittest individual before forced convergence.
#' @param trace TRUE/FALSE: Show trace?
#' 
#' @return A vector with two elements: the fittest decoded individual found in the entire run and its fitness.
#' @export
#' @example inst/examples/GACppwithR.R
GA_Cpp_with_R <- function(population_size, bitstring_size, fitness, lower, upper, maximum_number_of_iterations, tolerance, maximum_number_of_iterations_equal, trace = FALSE) {
    .Call('_simpleGA_GA_Cpp_with_R', PACKAGE = 'simpleGA', population_size, bitstring_size, fitness, lower, upper, maximum_number_of_iterations, tolerance, maximum_number_of_iterations_equal, trace)
}

